### ISSUE TITLE
Instalation via Pluginmanager fails

### ISSUE THREAD

**Issue by worldwidemv** [selfthinker/dokuwiki-plugin-loadskin#19]
Error Message: 
Das Erweiterungs-Verzeichnis konnte nicht identifiziert werden, laden und installieren sie die Datei manuell.

-> Extension directory could not be found, .....

I think this is because the tar.gz archive from github has only a directory called: 
selfthinker-dokuwiki-plugin-loadskin-ae64a40

Renaming this directory to loadskin, making a tar.gz file and using it manually with the plugin manager produces the same result.

I use Dokuwiki in version 2015-08-10 "Detritus".

Thanks in advance.

**Comment by selfthinker** [comment]
That's a bug in the DokuWiki core. See https://github.com/splitbrain/dokuwiki/issues/1296
Please upgrade to 2015-08-10**a**.
