### ISSUE TITLE
Issue with templates that have parameters in Configuration Manager

### ISSUE THREAD

**Issue by umbomas** [selfthinker/dokuwiki-plugin-loadskin#24]
Hi,
I have an issue when using the plugin loadskin together with a "configurable" template (_i.e._ a template that has its own section in the Configuration Manager page). The "configurable" template I refer to is bootstrap3.

My configuration is:
- wiki on localhost (Dokuwiki on a Stick)
- dokuwiki "standard" set as the default template
- bootstrap3 set as template for namespace playground:bootstrap3 (this setting is configured via "Loadskin Template Manager")

When I open the Configuration Manager, the section Template/Bootstrap3 is not shown.
- If I change the default template to be bootstrap3 (in this way bootstrap3 is applied to the whole wiki), the section Template/Bootstrap3 is shown and I can configure it.
- If I revert to my initial configuration, the section Template/Bootstrap3 disappear. However the configuration is saved and the same settings appear again if I change again the default template to bootstrap3.

I wonder if the problem is to be ascribed to loadskin.
Thanks in advance!

**Comment by selfthinker** [comment]
This is due to how DokuWiki handles template configurations. It is only possible to configure the currently activated template. (It is also not possible to configure de-activated plugins.) And it's not possible to change that (or rather, it's very difficult as it needs basic changes to the core).

The best workaround is to switch to each template, configure it and switch back to your chosen main template. The configuration of each template will be kept, as you already found out.

**Comment by selfthinker** [comment]
Hmm, I just thought of another workaround how to overcome this issue. Right now templates via loadskin deliberate don't work in the admin section and the main template will always be used. But I could make that configurable. So, if you click on the admin link when you are on a page which uses a different template, you could keep the template in the admin section. That way you can configure all templates without the need to really switch to them.

**Comment by selfthinker** [comment]
I have now implemented a config option to allow the template choice to persist in the admin section. That way you can see the configuration manager in different templates and therefore configure each of them separately without the need to activate the template properly in the config manager.

**Comment by umbomas** [comment]
Great! It works like a charm!

Thank you very much @selfthinker
