### ISSUE TITLE
Security Token did not match. Possible CSRF attack when loading LoadSkin Template Manager

### ISSUE THREAD

**Issue by huksley** [selfthinker/dokuwiki-plugin-loadskin#28]
Hello!

I am using Dokuwiki Release 2016-06-26a "Elenor of Tsort"

I am getting error when trying to access
LoadSkin Template Manager
from admin menu.

`Security Token did not match` 

Also, when I enter into namespace/page pattern field anything except empty 
and press Save nothing happens - nothing saved.

**Comment by simonxml** [comment]
I'm getting this error using 2015-08-10a "Detritus" too.

**Comment by ivchiga** [comment]
Same problem with 2016-06-26a "Elenor of Tsort"

Security Token did not match. Possible CSRF attack.

And nothing saved

**Comment by sesu85** [comment]
Hi everybody!
I read this explanation for the third time now, but I've still no idea how I get this running.
Was anybody able to fix this issue?
Thank you,
Sebastian

**Comment by selfthinker** [comment]
This is now fixed. Sorry it took me so long. (I don't check these things regularly.)
