### ISSUE TITLE
"User way: Select template for whole wiki" - not working in Greebo Release 2018-04-22b

### ISSUE THREAD

**Issue by emilracec** [selfthinker/dokuwiki-plugin-loadskin#33]
Dear friends,

I've just installed the plugin and it seems the "user way" is not showing up on the wiki. In more details, there is no dropdown the users can use to switch templates - as shown in the plugin docs.

Can you please help?

Thank you!

**Comment by ghbob** [comment]
@emilracec The problem is, that 'automaticOutput' is set to false per default, therefore the dropdown doesn't show.
See: https://www.dokuwiki.org/plugin:loadskin#configuration

**Comment by emilracec** [comment]
Thank you ghbob! Don't know how I missed that, solved.
